"""Template-based C# code generator for Revit family creation.

Converts ParameterAssignment --> compilable Revit API C# code.
CRITICAL: converts mm -> feet and degrees -> radians before emitting code.
"""

from __future__ import annotations

import math
from typing import Dict, Optional

from .parameter_space import ParameterAssignment, ParameterDomain, ParameterType


MM_TO_FT = 1.0 / 304.8


class ParameterResolver:
    """Resolves a ParameterAssignment into Revit API C# code."""

    def resolve(self, assignment: ParameterAssignment) -> str:
        space = assignment.parameter_space
        blocks: list[str] = [
            f"// Generated by Revit Family Engine -- space: {space.name}",
            "// NOTE: Revit internal units are feet for length, radians for angles",
            "",
        ]

        # Group by domain
        domains_present = {p.domain for p in space.parameters.values()}

        if ParameterDomain.FAMILY_PARAMETERS in domains_present:
            blocks.append(self._emit_family_parameters(assignment))
        if ParameterDomain.FAMILY_GEOMETRY in domains_present:
            blocks.append(self._emit_family_geometry(assignment))
        if ParameterDomain.GDT in domains_present:
            blocks.append(self._emit_gdt(assignment))
        if ParameterDomain.CONSTRAINTS in domains_present:
            blocks.append(self._emit_constraints(assignment))

        return "\n".join(b for b in blocks if b)

    # ------------------------------------------------------------------
    # Domain emitters
    # ------------------------------------------------------------------

    def _emit_family_parameters(self, assignment: ParameterAssignment) -> str:
        space = assignment.parameter_space
        lines = [
            "// --- Family Parameters ---",
            "FamilyManager famMgr = familyDoc.FamilyManager;",
            "FamilyType famType = famMgr.CurrentType ?? famMgr.NewType(\"Type 1\");",
        ]

        for name, param in space.parameters.items():
            if param.domain != ParameterDomain.FAMILY_PARAMETERS:
                continue
            value = assignment.get_value(name)

            if param.parameter_type in (
                ParameterType.LENGTH, ParameterType.WIDTH, ParameterType.HEIGHT,
                ParameterType.DEPTH, ParameterType.THICKNESS, ParameterType.OFFSET_VALUE,
            ):
                ft_val = float(value) * MM_TO_FT
                lines += [
                    f"FamilyParameter param_{_safe(name)} = famMgr.AddParameter(",
                    f'    "{name}", BuiltInParameterGroup.PG_GEOMETRY,',
                    f"    ParameterType.Length, {str(param.is_instance).lower()});",
                    f"famMgr.Set(param_{_safe(name)}, {ft_val:.6f}); // {value} mm",
                ]
            elif param.parameter_type == ParameterType.ANGLE:
                rad_val = float(value) * math.pi / 180.0
                lines += [
                    f"FamilyParameter param_{_safe(name)} = famMgr.AddParameter(",
                    f'    "{name}", BuiltInParameterGroup.PG_GEOMETRY,',
                    f"    ParameterType.Angle, {str(param.is_instance).lower()});",
                    f"famMgr.Set(param_{_safe(name)}, {rad_val:.6f}); // {value} deg",
                ]
            elif param.parameter_type == ParameterType.YES_NO_PARAM:
                int_val = 1 if value else 0
                lines += [
                    f"FamilyParameter param_{_safe(name)} = famMgr.AddParameter(",
                    f'    "{name}", BuiltInParameterGroup.PG_GEOMETRY,',
                    f"    ParameterType.YesNo, {str(param.is_instance).lower()});",
                    f"famMgr.Set(param_{_safe(name)}, {int_val});",
                ]
            elif param.parameter_type == ParameterType.MATERIAL_PARAM:
                lines += [
                    f"FamilyParameter param_{_safe(name)} = famMgr.AddParameter(",
                    f'    "{name}", BuiltInParameterGroup.PG_MATERIALS,',
                    f"    ParameterType.Material, {str(param.is_instance).lower()});",
                    f'// Set material by name: "{value}"',
                    f"ElementId matId = new FilteredElementCollector(familyDoc)",
                    f'    .OfClass(typeof(Material)).Cast<Material>()',
                    f'    .FirstOrDefault(m => m.Name == "{value}")?.Id ?? ElementId.InvalidElementId;',
                    f"if (matId != ElementId.InvalidElementId)",
                    f"    famMgr.Set(param_{_safe(name)}, matId);",
                ]
            else:
                # Numeric fallback
                lines += [
                    f"// Parameter: {name} = {value}",
                ]

        return "\n".join(lines)

    def _emit_family_geometry(self, assignment: ParameterAssignment) -> str:
        space = assignment.parameter_space
        lines = [
            "",
            "// --- Family Geometry (inside Transaction) ---",
            "using (Transaction tx = new Transaction(familyDoc, \"Create Geometry\"))",
            "{",
            "    tx.Start();",
            "",
        ]

        # Collect geometry params
        width = self._get_ft(assignment, ("Width", "b"))
        depth = self._get_ft(assignment, ("Depth", "d", "Thickness"))
        height = self._get_ft(assignment, ("Height", "Extrusion Depth"))

        direction = assignment.values.get("Extrusion Direction", "Positive")
        start_z = 0.0
        if direction == "Negative":
            end_z, start_z = 0.0, -height
        elif direction == "Symmetric":
            start_z, end_z = -height / 2, height / 2
        else:
            end_z = height

        lines += [
            f"    // Profile: {_fmt(width * 304.8)} x {_fmt(depth * 304.8)} mm",
            "    CurveArrArray profile = new CurveArrArray();",
            "    CurveArray loop = new CurveArray();",
            f"    double w = {width:.6f}; // feet",
            f"    double d = {depth:.6f}; // feet",
            "    XYZ p0 = new XYZ(-w/2, -d/2, 0);",
            "    XYZ p1 = new XYZ( w/2, -d/2, 0);",
            "    XYZ p2 = new XYZ( w/2,  d/2, 0);",
            "    XYZ p3 = new XYZ(-w/2,  d/2, 0);",
            "    loop.Append(Line.CreateBound(p0, p1));",
            "    loop.Append(Line.CreateBound(p1, p2));",
            "    loop.Append(Line.CreateBound(p2, p3));",
            "    loop.Append(Line.CreateBound(p3, p0));",
            "    profile.Append(loop);",
            "",
            "    SketchPlane sketchPlane = SketchPlane.Create(familyDoc,",
            "        Plane.CreateByNormalAndOrigin(XYZ.BasisZ, XYZ.Zero));",
            f"    Extrusion extrusion = familyDoc.FamilyCreate.NewExtrusion(",
            f"        true, profile, sketchPlane, {end_z:.6f});",
            f"    // extrusion start offset: {start_z:.6f} ft",
            "",
            "    tx.Commit();",
            "}",
        ]
        return "\n".join(lines)

    def _emit_gdt(self, assignment: ParameterAssignment) -> str:
        lines = ["", "// --- GD&T Annotations ---"]
        for name, param in assignment.parameter_space.parameters.items():
            if param.domain != ParameterDomain.GDT:
                continue
            value = assignment.get_value(name)
            if param.parameter_type == ParameterType.TOLERANCE_VALUE:
                tol_ft = float(value) * MM_TO_FT
                lines += [
                    f"// Tolerance: {name} = {value} mm ({tol_ft:.6f} ft)",
                    "DimensionType dimType = familyDoc.GetElement(",
                    "    new FilteredElementCollector(familyDoc).OfClass(typeof(DimensionType))",
                    "    .Cast<DimensionType>().First().Id) as DimensionType;",
                    f"dimType.get_Parameter(BuiltInParameter.DIM_TOL_SHOW).Set(1);",
                    f"dimType.get_Parameter(BuiltInParameter.DIM_TOL_TYPE).Set(2); // Symmetric",
                    f"dimType.get_Parameter(BuiltInParameter.DIM_TOL_VALUE).Set({tol_ft:.6f});",
                ]
        return "\n".join(lines)

    def _emit_constraints(self, assignment: ParameterAssignment) -> str:
        lines = ["", "// --- Constraints ---"]
        lines += [
            "// Reference planes for parametric constraints",
            "ReferencePlane refLeft = familyDoc.FamilyCreate.NewReferencePlane(",
            "    new XYZ(-1, 0, 0), new XYZ(-1, 1, 0), XYZ.BasisZ, activeView);",
            "ReferencePlane refRight = familyDoc.FamilyCreate.NewReferencePlane(",
            "    new XYZ(1, 0, 0), new XYZ(1, 1, 0), XYZ.BasisZ, activeView);",
            "refLeft.Name = \"Left\";",
            "refRight.Name = \"Right\";",
            "",
            "// Drive Width parameter by dimension between ref planes",
            "ReferenceArray refArr = new ReferenceArray();",
            "refArr.Append(refLeft.GetReference());",
            "refArr.Append(refRight.GetReference());",
            "Dimension widthDim = familyDoc.FamilyCreate.NewLinearDimension(",
            "    activeView, Line.CreateBound(new XYZ(-2, 0, 0), new XYZ(2, 0, 0)), refArr);",
            "if (widthDim != null && widthDim.IsReferencesValidForLabel())",
            "{",
            "    FamilyParameter widthParam = famMgr.get_Parameter(\"Width\");",
            "    if (widthParam != null) widthDim.FamilyLabel = widthParam;",
            "}",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_ft(self, assignment: ParameterAssignment, names: tuple) -> float:
        for n in names:
            if n in assignment.values:
                v = float(assignment.values[n])
                param = assignment.parameter_space.parameters.get(n)
                if param and param.unit == "mm":
                    return v * MM_TO_FT
                return v
        return 1.0  # fallback 1 foot


def _safe(name: str) -> str:
    return name.replace(" ", "_").replace("/", "_").replace("-", "_").lower()


def _fmt(mm: float) -> str:
    return f"{mm:.0f}"
